# Generated by Django 2.2.13 on 2022-09-14 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='guesthouse_rooms',
            fields=[
                ('room_id', models.IntegerField(primary_key=True, serialize=False)),
                ('room_type', models.CharField(choices=[('AC', 'A/C'), ('Non A/C', 'Non A/C'), ('VIP', 'VIP')], default=('AC', 'A/C'), max_length=200)),
                ('room_desc', models.CharField(max_length=400)),
                ('room_rent', models.IntegerField()),
                ('room_available', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
