# Generated by Django 2.2.13 on 2022-09-14 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guesthouse', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guesthouse_rooms',
            name='room_available',
        ),
    ]
