# Generated by Django 2.2.13 on 2022-09-14 23:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('guesthouse', '0002_remove_guesthouse_rooms_room_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='guesthouse_rooms',
            name='room_available',
            field=models.IntegerField(),
            preserve_default=False,
        ),
    ]
