# Generated by Django 2.2.24 on 2022-09-17 16:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('guesthouse', '0003_guesthouse_rooms_room_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='guesthouse_rooms',
            name='room_img',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='guestHouse/'),
            preserve_default=False,
        ),
    ]
