# Generated by Django 2.2.24 on 2022-09-17 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guesthouse', '0004_guesthouse_rooms_room_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guesthouse_rooms',
            name='room_type',
            field=models.CharField(max_length=200),
        ),
    ]
