# Generated by Django 2.2.24 on 2022-09-17 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guesthouse', '0005_auto_20220917_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guesthouse_rooms',
            name='room_img',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
