# Generated by Django 2.2.24 on 2022-09-18 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guesthouse', '0006_auto_20220917_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guesthouse_rooms',
            name='room_img',
            field=models.ImageField(upload_to='guestHouse'),
        ),
    ]
