# Generated by Django 2.2.24 on 2022-09-18 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guesthouse', '0007_auto_20220918_0446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guesthouse_rooms',
            name='room_img',
            field=models.ImageField(blank=True, null=True, upload_to='guest_house/'),
        ),
    ]
