# Generated by Django 2.2.24 on 2022-12-08 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guesthouse', '0008_auto_20220918_0505'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookingDetails',
            fields=[
                ('booking_id', models.IntegerField(primary_key=True, serialize=False)),
                ('room_type', models.CharField(max_length=200)),
                ('number_of_rooms', models.IntegerField()),
                ('check_in', models.DateField(blank=True, null=True)),
                ('check_out', models.DateField(blank=True, null=True)),
                ('person_name', models.CharField(max_length=200)),
                ('room_rate', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
                ('number_of_persons', models.IntegerField()),
            ],
        ),
    ]
