# Generated by Django 2.2.24 on 2022-12-11 10:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('guesthouse', '0009_bookingdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingdetails',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
