# Generated by Django 2.2.24 on 2022-12-11 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guesthouse', '0011_auto_20221211_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingdetails',
            name='status',
            field=models.IntegerField(),
        ),
    ]
