# Generated by Django 2.2.24 on 2022-08-02 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentHead',
            fields=[
                ('head_id', models.AutoField(primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=100)),
                ('head_name', models.CharField(max_length=200, null=True)),
                ('head_mail', models.EmailField(max_length=254)),
                ('head_username', models.CharField(max_length=100)),
                ('head_password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=200)),
                ('department_email', models.EmailField(max_length=254)),
                ('department_username', models.CharField(max_length=100)),
                ('department_password', models.CharField(max_length=100)),
                ('head_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.DepartmentHead')),
            ],
        ),
    ]
