# Generated by Django 2.2.24 on 2022-08-03 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='head_id',
            new_name='head_ids',
        ),
    ]
