# Generated by Django 2.2.24 on 2022-08-05 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220803_0806'),
    ]

    operations = [
        migrations.CreateModel(
            name='Main_accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('position', models.IntegerField(null=True)),
                ('varification_choices', models.CharField(choices=[('Varification', 'Varification'), ('Non Varification', 'Non Varification')], default=('Varification', 'Varification'), max_length=100)),
            ],
        ),
    ]
