# Generated by Django 2.2.24 on 2022-08-08 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_main_accounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main_accounts',
            name='position',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
