# Generated by Django 2.2.24 on 2022-08-08 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20220808_0434'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmenthead',
            name='status',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
