# Generated by Django 2.2.24 on 2022-08-08 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_departmenthead_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmenthead',
            name='status',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
