# Generated by Django 2.2.13 on 2022-08-10 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20220810_1156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='main_accounts',
            name='position',
        ),
    ]
