# Generated by Django 4.1.1 on 2022-10-05 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_remove_departmenthead_head_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="department",
            name="department_username",
        ),
        migrations.RemoveField(
            model_name="main_accounts",
            name="username",
        ),
    ]
