# Generated by Django 2.2.13 on 2022-09-21 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pro_art_instrument', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('Category_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Category_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Hall_details',
            fields=[
                ('Hall_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Hall_name', models.CharField(max_length=200)),
                ('Hall_capacity', models.IntegerField()),
                ('Hall_location', models.CharField(max_length=200)),
                ('Hall_infrastructrure', models.CharField(blank=True, max_length=200)),
                ('Hall_availability', models.CharField(choices=[('Available', 'Available'), ('Not Available', 'Not Available')], default=('Available', 'Available'), max_length=20)),
                ('Hall_spesification', models.CharField(choices=[('AC', 'A/C'), ('Non A/C', 'Non A/C')], default=('AC', 'A/C'), max_length=20)),
                ('Hall_manager', models.CharField(max_length=100)),
                ('public_view', models.BooleanField(default=False)),
                ('Amount', models.IntegerField(blank=True, null=True)),
                ('Due_date', models.DateField(blank=True, null=True)),
                ('NewAmount', models.IntegerField(blank=True, null=True)),
                ('Hall_images', models.ImageField(blank=True, null=True, upload_to='hallimage/')),
            ],
        ),
        migrations.CreateModel(
            name='payment_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Event_id', models.IntegerField()),
                ('Challan_number', models.CharField(max_length=200)),
                ('Payment_datetime', models.DateTimeField()),
                ('Amount', models.IntegerField()),
                ('Treasury', models.CharField(max_length=200)),
                ('Payer_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.IntegerField()),
                ('approved_by', models.CharField(max_length=200)),
                ('approved_on', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Event_registration',
            fields=[
                ('Event_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Event_name', models.CharField(max_length=200)),
                ('Event_startDate', models.DateField()),
                ('Event_endDate', models.DateField()),
                ('Event_description', models.CharField(blank=True, max_length=200)),
                ('Event_status', models.IntegerField(default=0)),
                ('Event_manager', models.CharField(max_length=200)),
                ('public', models.BooleanField(default=False)),
                ('Resubmission', models.IntegerField(default=0)),
                ('waiting_list', models.IntegerField(default=0)),
                ('Event_amount', models.IntegerField(blank=True, null=True)),
                ('Category_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pld.EventCategory')),
                ('Event_venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pld.Hall_details')),
                ('Instrument_details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pro_art_instrument.instrument_details')),
            ],
        ),
    ]
