# Generated by Django 2.2.13 on 2022-09-21 00:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pld', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_registration',
            name='Instrument_details',
            field=models.CharField( max_length=200),
            preserve_default=False,
        ),
    ]
