# Generated by Django 2.2.13 on 2022-09-21 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pld', '0002_auto_20220921_0557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_registration',
            name='Instrument_details',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
