# Generated by Django 2.2.13 on 2022-09-23 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pld', '0003_auto_20220921_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_registration',
            name='Art_and_Photography',
            field=models.BooleanField(default=False),
        ),
    ]
