# Generated by Django 2.2.13 on 2022-09-23 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pld', '0004_event_registration_art_and_photography'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_registration',
            name='art_permission',
            field=models.IntegerField(default=0),
        ),
    ]
