# Generated by Django 2.2.13 on 2022-09-23 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pld', '0006_event_registration_event_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_registration',
            name='Event_images',
            field=models.ImageField(blank=True, null=True, upload_to='hallimage/'),
        ),
    ]
