# Generated by Django 2.2.13 on 2022-09-23 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pld', '0007_auto_20220923_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_registration',
            name='Image_description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='event_registration',
            name='Event_images',
            field=models.ImageField(blank=True, null=True, upload_to='Eventimage/'),
        ),
    ]
