# Generated by Django 4.1.1 on 2022-10-09 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pld", "0008_auto_20220924_0526"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event_log",
            fields=[
                ("log_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("operation", models.CharField(max_length=200)),
                ("person_name", models.CharField(max_length=200)),
                ("person_category", models.CharField(max_length=200)),
                ("Event_id", models.IntegerField()),
            ],
        ),
    ]
