# Generated by Django 2.2.24 on 2022-10-17 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pld', '0012_alter_event_log_event_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall_details',
            name='Hall_availability',
            field=models.BooleanField(default=False),
        ),
    ]
