# Generated by Django 2.2.24 on 2022-10-17 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pld', '0013_auto_20221017_0537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hall_details',
            name='Hall_infrastructrure',
        ),
        migrations.AlterField(
            model_name='hall_details',
            name='Hall_id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
