# Generated by Django 2.2.24 on 2022-12-04 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pld', '0016_auto_20221205_0513'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_registration',
            name='Event_startTime',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
