# Generated by Django 2.2.24 on 2022-12-08 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pld', '0018_event_registration_guest_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_registration',
            name='Event_images',
            field=models.FileField(blank=True, null=True, upload_to='Eventimage/'),
        ),
    ]
