# Generated by Django 2.2.24 on 2022-12-12 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pld', '0020_auto_20221208_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_registration',
            name='Category_name',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
