# Generated by Django 2.2.13 on 2022-08-09 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Unions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unions',
            old_name='Secretary_name',
            new_name='secretary_name',
        ),
    ]
