# Generated by Django 2.2.13 on 2022-08-09 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Unions', '0002_auto_20220809_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='unions',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
