# Generated by Django 4.1.1 on 2022-09-30 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Unions", "0003_unions_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="unions",
            name="union_username",
        ),
    ]
