# Generated by Django 2.2.13 on 2022-08-10 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='public_registration',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='public_registration',
            name='location',
            field=models.CharField(max_length=200),
        ),
    ]
