# Generated by Django 2.2.13 on 2022-08-10 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0002_auto_20220810_1449'),
    ]

    operations = [
        migrations.RenameField(
            model_name='public_registration',
            old_name='address',
            new_name='public_address',
        ),
        migrations.RenameField(
            model_name='public_registration',
            old_name='email',
            new_name='public_email',
        ),
        migrations.RenameField(
            model_name='public_registration',
            old_name='location',
            new_name='public_location',
        ),
        migrations.RenameField(
            model_name='public_registration',
            old_name='name',
            new_name='public_name',
        ),
        migrations.RenameField(
            model_name='public_registration',
            old_name='password',
            new_name='public_password',
        ),
        migrations.RenameField(
            model_name='public_registration',
            old_name='phone',
            new_name='public_phone',
        ),
        migrations.RenameField(
            model_name='public_registration',
            old_name='username',
            new_name='public_username',
        ),
    ]
