# Generated by Django 4.1.1 on 2022-09-30 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("public", "0003_auto_20220810_1542"),
    ]

    operations = [
        migrations.AddField(
            model_name="public_registration",
            name="status",
            field=models.IntegerField(default=0),
        ),
    ]
